MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.fpn_ResNet101_conv5_body
  FASTER_RCNN: True
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet101_caffe.pth'
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0002
  GAMMA: 0.1
  MAX_ITER: 10000
  STEPS: [0, 5000, 8000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEAK_SUPERVISE: True
  WEAK_SUPERVISE_WITH_PRETRAIN: True
  COPY_CLS_TO_DET: True
  FREEZE_CONV_BODY: True
  FREEZE_RPN: True
  SCALES: (600,)
  MAX_SIZE: 1000
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  SNAPSHOT_ITERS: 2000 
  IMS_PER_BATCH: 4
TEST:
  SCALE: 600
  MAX_SIZE: 1000
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000

